services:
  db:
    image: postgres:9
    ports:
      - "9999:5432"
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tawori_db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: {}